### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by zhaizhibo** [uqzhichen/SDGZSL#1]
"missing the CUB dataset."  How can I get the visual features of CUB dataset(not the visual features extracted from the pre-trained deep models)

**Comment by uqzhichen** [comment]
Hi Kern,

The data.mat file is the visual features for CUB dataset. You can refer to the dataloader how to load the visual features.

Regards,
Zhi

**Comment by zhaizhibo** [comment]
> Hi Kern,
> 
> The data.mat file is the visual features for CUB dataset. You can refer to the dataloader how to load the visual features.
> 
> Regards, Zhi

Thanks for your reply! I have downloaded the dataset. But I was confused by the "data.mat", could you please explain the meaning of each filed in the "data.mat", such as  "seen_pro", "train_fea", "train_pro" etc.

**Comment by uqzhichen** [comment]
The dataset is actually from EPGN(CVPR2020) https://github.com/yunlongyu/EPGN, which is mentioned in the README file. seen_pro is the class embeddings for seen classes, train_fea is the visual features of seen classes. You can refer to the dataloader for more details. https://github.com/uqzhichen/SDGZSL/blob/beed9df03d6f7f0ce6e71753b346da670345a861/dataset_GBU.py#L97-L108
