### ISSUE TITLE
Could you provide the results of CUB using attributes

### ISSUE THREAD

**Issue by NanAlbert** [uqzhichen/SDGZSL#2]
I directly used your code to train the model using CUB attributes, but the results were pretty poor (H is less than 0.50). I guess it's a matter of parameter settings. So could you provide the results of CUB using attributes, or the corresponding parameter settings?  It would be better if you could also provide the results or the parameters of the SUN dataset. Thank you!

**Comment by uqzhichen** [comment]
Hi Albert,

Thank you for your attention to our paper. I will try to release your required results recently. Hopefully, I could put some time on this after the CVPR deadline.

Cheers,
Zhi

**Comment by NanAlbert** [comment]
Waiting for your results and new work on CVPR. Best Wishes.

**Comment by HanAccount** [comment]
> Waiting for your results and new work on CVPR. Best Wishes.

Hi! Do you know what happens when I have the following problems while training？
No changes to the code！run train_AWA2.py

Traceback (most recent call last):
  File "/home/idea/hay/SDGZSL/train_AWA2.py", line 293, in <module>
    train()
  File "/home/idea/hay/SDGZSL/train_AWA2.py", line 69, in train
    dataset = DATA_LOADER(opt)
  File "/home/idea/hay/SDGZSL/dataset_GBU.py", line 21, in __init__
    self.read_matdataset(opt)
  File "/home/idea/hay/SDGZSL/dataset_GBU.py", line 206, in read_matdataset
    self.test_seen_label = map_label(self.test_seen_label, self.seenclasses)
AttributeError: 'DATA_LOADER' object has no attribute 'test_seen_label'

**Comment by NanAlbert** [comment]
The error is clear. There is no self.test_seen_label. You can refer to self.test_unseen_label and add the codes for self.test_seen_label.
(  After self.test_unseen_label = torch.from_numpy(label[val_unseen_loc]).long() )
I haven't tried to modify it yet, but it should work. I hope I can help you.

**Comment by NanAlbert** [comment]
> 

The error is clear. There is no self.test_seen_label. You can refer to self.test_unseen_label and add the codes for self.test_seen_label.
( After self.test_unseen_label = torch.from_numpy(label[val_unseen_loc]).long() )
I haven't tried to modify it yet, but it should work. I hope I can help you.

**Comment by NanAlbert** [comment]
> > Waiting for your results and new work on CVPR. Best Wishes.
> 
> Hi! Do you know what happens when I have the following problems while training？ No changes to the code！run train_AWA2.py
> 
> Traceback (most recent call last): File "/home/idea/hay/SDGZSL/train_AWA2.py", line 293, in train() File "/home/idea/hay/SDGZSL/train_AWA2.py", line 69, in train dataset = DATA_LOADER(opt) File "/home/idea/hay/SDGZSL/dataset_GBU.py", line 21, in **init** self.read_matdataset(opt) File "/home/idea/hay/SDGZSL/dataset_GBU.py", line 206, in read_matdataset self.test_seen_label = map_label(self.test_seen_label, self.seenclasses) AttributeError: 'DATA_LOADER' object has no attribute 'test_seen_label'

The error is clear. It lacks the definition of self.test_seen_label. You can refer to the definition of self.test_unseen_label and add the codes for self.test_seen_label. (After self.test_unseen_label = torch.from_numpy(label[val_unseen_loc]).long() )
I haven't tried to fix it yet, but it should work. I hope this can help you.

**Comment by uqzhichen** [comment]
> 

Hi Han,

If you set the hyper-parameter validation to false, it will be solved. 

Cheers,
Zhi

**Comment by HanAccount** [comment]
Hi！Thank you very much for your comments！ 
The experiments have all been run successfully！
How many folders will each dataset generate after you run the experiment？
Why does AWA2 generate four folders？
![image](https://user-images.githubusercontent.com/87269265/143545086-dc3fc1a5-2196-43f3-94e6-46131aadb3f7.png)

**Comment by uqzhichen** [comment]
Hi Han,

Each folder is corresponding to one experiment. For example, in APY, when you change the hyparameter gamma (g-0.3), there is another folder saving the results.

Cheers,
Zhi

**Comment by HanAccount** [comment]
There are three .py files for each dataset，How do these three files work during training？
I'm running all three files respectively on three gpus!

**Comment by uqzhichen** [comment]
They are for different datasets and independent of each other.

**Comment by HanAccount** [comment]
I directly used your code but could not reach the results of the paper,Is there any other parameter setting?

The results of backbone without fine-tunes are as follows

eg CUB: H(62.58) S(63.75) U(61.45)
Can not reach the expected effect of the paper!
The GPU is RTX2080

**Comment by uqzhichen** [comment]
Hi Han, the result I reported is 63 on H, the 0.42 gap is acceptable and may due to the device difference. Mine is 2080Ti.

**Comment by HanAccount** [comment]
Thanks a lot!

**Comment by uqzhichen** [comment]
> I directly used your code to train the model using CUB attributes, but the results were pretty poor (H is less than 0.50). I guess it's a matter of parameter settings. So could you provide the results of CUB using attributes, or the corresponding parameter settings? It would be better if you could also provide the results or the parameters of the SUN dataset. Thank you!

Hi Albert,

I have provided the experimental results on the CUB dataset with attributes, SUN dataset, and the FLO dataset without normalization.

Cheers,
Zhi

**Comment by NanAlbert** [comment]
> > I directly used your code to train the model using CUB attributes, but the results were pretty poor (H is less than 0.50). I guess it's a matter of parameter settings. So could you provide the results of CUB using attributes, or the corresponding parameter settings? It would be better if you could also provide the results or the parameters of the SUN dataset. Thank you!
> 
> Hi Albert,
> 
> I have provided the experimental results on the CUB dataset with attributes, SUN dataset, and the FLO dataset without normalization.
> 
> Cheers, Zhi

Thank you so much!
