### ISSUE TITLE
关于评估指标

### ISSUE THREAD

**Issue by HanAccount** [uqzhichen/SDGZSL#4]
你好：
我看到你的scripts文件夹中的命令后面有运行的结果，但是与你的论文里的差别有点大
比如在CUB数据集中 没有使用finetune的论文结果是 H：63.0  T1：75.5
但是代码里给的是：H：54.89  T1：62.75

使用finetune的结果也有差别

这是什么情况呢

**Comment by uqzhichen** [comment]
Hi Han,

The semantic embeddings of the higher result in the paper is the CNN-RNN sentence embeddings, which are also widely used in the compared methods, e.g., EPGN. But as per request, we also provide the results with attributes as the semantic information.

Cheers,
Zhi

**Comment by HanAccount** [comment]
> Hi Han,
> 
> The semantic embeddings of the higher result in the paper is the CNN-RNN sentence embeddings, which are also widely used in the compared methods, e.g., EPGN. But as per request, we also provide the results with attributes as t
