### ISSUE TITLE
t-SNE可视化代码

### ISSUE THREAD

**Issue by HanAccount** [uqzhichen/SDGZSL#7]
您好：
能麻烦您提供一下t-SNE可视化代码吗?我发现在代码里只保存了VAE的模型文件并没有保存解纠缠模块的文件是为什么呢？

**Comment by uqzhichen** [comment]
Hi Han,

You could use the t-SNE package in sklearn library to visualize the representations, which should be easy to implement.

For the model saving, I'll update the code to save the disentangling module as well.

regards,
Zhi

**Comment by HanAccount** [comment]
非常感谢！
