### ISSUE TITLE
FLO-GBU and FLO-EPGN

### ISSUE THREAD

**Issue by yangjingqi99** [uqzhichen/SDGZSL#8]
Dear Author， May I ask what is the difference between the visual features given by FLO-GBU and FLO-EPGN? The paper you mentioned (Zero-Shot Learning The Good, the Bad and the Ugly) does not have FLO settings, so what is  FLO-GBU ?

**Comment by uqzhichen** [comment]
Hi Jingqi,

Thank you for your interest on my work.

Sorry about the confusion. FLO is actually introduced in [1] but not [2]. As the two papers from the same author, I just say FLO-GBU. 

I noticed the dataset difference between FLO[1] and FLO-EPGN after SDGZSL is published.  I asked the authors of EPGN about the difference, they mentioned that they did further normalizaion on the dataset. 

I hope the above explanation could be helpful.

[1] Feature Generating Networks for Zero-Shot Learning
[2] Zero-Shot Learning The Good, the Bad and the Ugly

Best regards,
Zhi

**Comment by yangjingqi99** [comment]
> 
Thank you for your patient response, it helps me a lot!
